#!/usr/bin/env python3
"""
Fetch a user's public, non-fork, non-archived repos and print them as TOML on stdout,
most recently pushed first. Consumed by templates/projects.html via load_data().

Usage:
    python3 scripts/fetch_all_github_projects.py <username> > content/projects/data.toml
"""
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime
from typing import Any

API = "https://api.github.com"
PER_PAGE = 100


def get(url: str) -> list[dict[str, Any]]:
    request = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "ms-choudhary.github.io-build",
    })
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(request, timeout=30) as response:
        payload: list[dict[str, Any]] = json.load(response)
    return payload


def fetch_repos(username: str) -> list[dict[str, Any]]:
    repos: list[dict[str, Any]] = []
    page = 1
    while True:
        query = urllib.parse.urlencode({
            "page": page, "per_page": PER_PAGE, "type": "owner",
            "sort": "pushed", "direction": "desc",
        })
        batch = get(f"{API}/users/{username}/repos?{query}")
        repos.extend(batch)
        print(f"  page {page}: {len(batch)} repos", file=sys.stderr)
        if len(batch) < PER_PAGE:
            return repos
        page += 1


def is_publishable(repo: dict[str, Any]) -> bool:
    return not repo.get("fork") and not repo.get("archived") and bool(repo.get("description"))


def month_year(timestamp: str) -> str:
    try:
        return datetime.fromisoformat(timestamp.replace("Z", "+00:00")).strftime("%b %Y")
    except ValueError:
        return ""


def toml_string(value: str) -> str:
    """Quote a TOML basic string: backslash first, then quotes, then control chars."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{escaped}"'


def as_toml(repo: dict[str, Any]) -> str:
    lines = ["[[project]]", f"name = {toml_string(repo['name'])}",
             f"description = {toml_string(repo['description'])}"]

    for key, timestamp in (("created", repo.get("created_at")), ("pushed", repo.get("pushed_at"))):
        formatted = month_year(timestamp) if timestamp else ""
        if formatted:
            lines.append(f"{key} = {toml_string(formatted)}")

    if repo.get("stargazers_count", 0) > 10:
        lines.append(f"stars = {repo['stargazers_count']}")
    if repo.get("language"):
        lines.append(f"language = {toml_string(repo['language'])}")

    lines.append("links = [")
    homepage = (repo.get("homepage") or "").strip()
    if homepage:
        lines.append(f"  {{ name = \"Homepage\", url = {toml_string(homepage)} }},")
    lines.append(f"  {{ name = \"GitHub\", url = {toml_string(repo['html_url'])} }},")
    lines.append("]")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <github-username>")
    username = sys.argv[1]

    print(f"Fetching repositories for {username}...", file=sys.stderr)
    try:
        repos = fetch_repos(username)
    except urllib.error.HTTPError as error:
        sys.exit(f"GitHub API error {error.code}: {error.reason}")
    except urllib.error.URLError as error:
        sys.exit(f"could not reach GitHub: {error.reason}")

    publishable = sorted(
        (repo for repo in repos if is_publishable(repo)),
        key=lambda repo: repo.get("pushed_at") or "",
        reverse=True,
    )
    if not publishable:
        sys.exit(f"no publishable repos found for {username}")

    skipped = [repo["name"] for repo in repos
               if not repo.get("fork") and not repo.get("archived")
               and not repo.get("description")]
    print(f"{len(repos)} repos, publishing {len(publishable)}", file=sys.stderr)
    if skipped:
        print(f"skipped (no GitHub description): {', '.join(sorted(skipped))}", file=sys.stderr)

    print("# GitHub projects, generated by scripts/fetch_all_github_projects.py")
    print(f"# {len(publishable)} projects")
    print()
    for repo in publishable:
        print(as_toml(repo))
        print()


if __name__ == "__main__":
    main()
