name: Zola on GitHub Pages

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [til-updated]

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: "recursive"
          fetch-depth: 0

      - name: Generate notes from til
        run: make notes

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Fetch project metadata from GitHub
        run: make projects

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
